### ISSUE TITLE
Instead of open in a popup it redirect to google play store. 

### ISSUE THREAD

**Issue by brnaidu08** [chemerisuk/cordova-plugin-app-review#10]
![WhatsApp Image 2021-09-15 at 11 42 16 AM](https://user-images.githubusercontent.com/56384084/133397003-0ef0df3e-d9fb-49b3-aa61-e39b59cd35ed.jpeg)

I tested Inreview APP it is working good but the issue is that not opened in the app as popup. it redirect to google play store. pleas suggest me the correction

**Comment by chemerisuk** [comment]
@brnaidu08 have you read android notes in read me? https://github.com/chemerisuk/cordova-plugin-app-review#requestreview
