### ISSUE TITLE
requestReview() -> "can't get trackId"

### ISSUE THREAD

**Issue by c0sm1cdus7** [chemerisuk/cordova-plugin-app-review#11]
Hey everyone I came across an error on the `cordova.plugins.AppReview.openStoreScreen();` function running on iOS.

Upon calling it i get an error saying `Can't get trackId`.

I also tried calling `cordova.plugins.AppReview.openStoreScreen(PACKAGE_NAME);` but got the same result.

Anyone came across this and managed to solve it?

**Comment by nitrovolnovka** [comment]
So what's the solution? :)

**Comment by nitrovolnovka** [comment]
I'll answer this myself. It will show this error until the application is published to App Store.
