### ISSUE TITLE
Library update

### ISSUE THREAD

**Issue by fredriksthlm** [chemerisuk/cordova-plugin-app-review#13]
There is an update from Google that you now only need to include the review library, not the full Core library any longer!

Dependency:
**com.google.android.play:review:2.0.0**
 instead of
**com.google.android.play:core**

Release notes:
https://developer.android.com/reference/com/google/android/play/core/release-notes

There is an easy migration guide here:
https://developer.android.com/guide/playcore#playcore-migration

**Comment by chemerisuk** [comment]
@fredriksthlm this is a good change indeed. Do you have time to submit PR with it? I’m very busy these days…

**Comment by fredriksthlm** [comment]
> @fredriksthlm this is a good change indeed. Do you have time to submit PR with it? I’m very busy these days…

Look into this: https://github.com/chemerisuk/cordova-plugin-app-review/pull/14

**Comment by fredriksthlm** [comment]
@chemerisuk 
Will you update the npm as well?
(I didnt update your description page regarding the method to set Core version. I guess you can just remove that part, since the core package should not be loaded)

**Comment by mayainle** [comment]
Hmm, for some reason I don't get the review dialog any longer. Even when I try with a completely new Google Play account. This was the latest change right? Did it work for you guys?

**Comment by chemerisuk** [comment]
@mayainle I apologise there was a bug in the latest update. It was fixed in 2.1.3, try to install it instead.

**Comment by mayainle** [comment]
@chemerisuk perfect thank you :)

**Comment by mayainle** [comment]
@chemerisuk it is probably not an plugin issue but I never get the rating window and it is not because of testing since it doesn't even work for google accounts in the live app that never saw the rating window before (not a quota issue) but I see in logcat an error:

```
PlayCore: UID: [10107]  PID: [6672] ReviewService : linkToDeath
08-12 18:29:46.759  3881  3918 I System.out: Caught a exception encoding the public key: com.android.apksig.internal.asn1.Asn1DecodingException: Failed to parse eee.a
08-12 18:29:46.760  3881  3918 W System.err: com.android.apksig.internal.asn1.Asn1DecodingException: Failed to parse eee.a
08-12 18:29:46.760  3881  3918 W System.err: Caused by: com.android.apksig.internal.asn1.Asn1BerParser$Asn1UnexpectedTagException: Tag mismatch. Expected: UNIVERSAL BIT STRING, but found UNIVERSAL SEQUENCE
```


Do you maybe have an idea what I'm missing. I tried to google but can't find anything?
