### ISSUE TITLE
callbackContext declare as final error

### ISSUE THREAD

**Issue by salmanshariff92** [chemerisuk/cordova-plugin-app-review#4]
getting this error while running on android
java/by/chemerisuk/cordova/AppReviewPlugin.java:39: error: local variable callbackContext is accessed from within inner class; needs to be declared final
                    respondWith(task.getException(), callbackContext);

**Comment by chemerisuk** [comment]
@salmanshariff92 thanks for the report. The issue should be fixed in v2.0.3
