### ISSUE TITLE
Application build Failed error:  Could not find com.google.android.play:core:'1.8.+' ionic v3

### ISSUE THREAD

**Issue by sksk008** [chemerisuk/cordova-plugin-app-review#7]
> cordova.cmd build android --device
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=C:\Users\ADMIN\AppData\Local\Android\Sdk (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: C:\Users\ADMIN\AppData\Local\Android\Sdk
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.play:core:'1.8.+'.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/play/core/'1.8.+'/core-'1.8.+'.pom
       - https://jcenter.bintray.com/com/google/android/play/core/'1.8.+'/core-'1.8.+'.pom
       - https://repo.maven.apache.org/maven2/com/google/android/play/core/'1.8.+'/core-'1.8.+'.pom
     Required by:
         project :app

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
7 actionable tasks: 1 executed, 6 up-to-date
Command failed with exit code 1: C:\user\example\example\platforms\android\gradlew cdvBuildDebug -b C:\user\example\example\platforms\android\build.gradle
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android --device exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by MarcelSchuermann** [comment]
I got the same error when using the variable "`--variable ANDROID_PLAY_CORE_VERSION='1.8.+`’" 
Error: «`Could not find com.google.android.play:core:'1.8.+'`.”
I am using cordova version 10.0.0

Any idea?

When installing without the variable "`cordova plugin add cordova-plugin-app-review`" I nothing happends when running `requestReview()` but I get following log in Android Studio:
```
 I/PlayCore: UID: [10376]  PID: [14377] ReviewService : requestInAppReview (com.FindSecrets.FoodSecrets)
I/PlayCore: UID: [10376]  PID: [14377] ReviewService : Initiate binding to the service.
I/PlayCore: UID: [10376]  PID: [14377] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore: UID: [10376]  PID: [14377] ReviewService : linkToDeath
I/PlayCore: UID: [10376]  PID: [14377] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
I/PlayCore: UID: [10376]  PID: [14377] ReviewService : Unbind from service.
D/CordovaActivity: Paused the activity.
D/CordovaActivity: Resumed the activity.
D/NetworkManager: toLower : wifi
    Connection Type: wifi
    Networkinfo state didn't change, there is no event propagated to the JavaScript side.
```

Any help is highly appreciated.

**Comment by MarcelSchuermann** [comment]
> I got the same error when using the variable "`--variable ANDROID_PLAY_CORE_VERSION='1.8.+`’"
> Error: «`Could not find com.google.android.play:core:'1.8.+'`.”
> I am using cordova version 10.0.0
> 
> Any idea?
> 
> When installing without the variable "`cordova plugin add cordova-plugin-app-review`" I nothing happends when running `requestReview()` but I get following log in Android Studio:
> 
> ```
>  I/PlayCore: UID: [10376]  PID: [14377] ReviewService : requestInAppReview (com.FindSecrets.FoodSecrets)
> I/PlayCore: UID: [10376]  PID: [14377] ReviewService : Initiate binding to the service.
> I/PlayCore: UID: [10376]  PID: [14377] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
> I/PlayCore: UID: [10376]  PID: [14377] ReviewService : linkToDeath
> I/PlayCore: UID: [10376]  PID: [14377] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
> I/PlayCore: UID: [10376]  PID: [14377] ReviewService : Unbind from service.
> D/CordovaActivity: Paused the activity.
> D/CordovaActivity: Resumed the activity.
> D/NetworkManager: toLower : wifi
>     Connection Type: wifi
>     Networkinfo state didn't change, there is no event propagated to the JavaScript side.
> ```
> 
> Any help is highly appreciated.

I installed the plugin without the variable and followed following instructions:
https://stackoverflow.com/questions/63286540/play-core-in-app-review-api-not-showing-the-review-activity?answertab=active#tab-top

This way I could run the feedback dialog in release mode on the mobile phone.
