### ISSUE TITLE
Uncaught TypeError: Cannot read property 'AppReview' of undefined

### ISSUE THREAD

**Issue by keev-studio** [chemerisuk/cordova-plugin-app-review#9]
Hi, Using Cordova 10.0
and after installing plugin cordova-plugin-app-review

and calling - cordova.plugins.AppReview.requestReview(); 
I am getting 
Uncaught TypeError: Cannot read property 'AppReview' of undefined
anyone know why?
thank you

**Comment by brnaidu08** [comment]
Hi, Using Cordova 
and after installing plugin cordova-plugin-app-review

and calling - cordova.plugins.AppReview.requestReview();
I am getting
Uncaught TypeError: Cannot read property 'AppReview' of undefined
anyone know why?
thank you

**Comment by Patogomezfa** [comment]
+1

**Comment by Luciano-Tarsia** [comment]
Hi keev. Did you manage to solve this error? I'm running into the same problem and i cant find the reason

**Comment by keev-studio** [comment]
Hi, somehow the error disappeared reverting to:
cordova 10.1
gradle-6.7.1
java 1.8.0

I will do more tests with updates stack when I have more time. Please let me know if you have any progress on this
